### ISSUE TITLE
Migrate build to sbt-typelevel

### ISSUE THREAD

**Issue by lenguyenthanh** [davenverse/shellfish#55]
The current build with [sbt plugins](https://github.com/davenverse/shellfish/blob/main/project/plugins.sbt) are a bit out of date. I was struggled a little bit before gave up bumping those plugins.

I think We should try to migrate to the commonly used [sbt-typelevel](https://github.com/typelevel/sbt-typelevel).

We can look at the recent [sbt-typelevel migration PR](https://github.com/typelevel/weaver-test/pull/8) in `weaver-dev` as an example.

What do you think? @Hombre-x @zetashift @TonioGela @armanbilge?

**Comment by Hombre-x** [comment]
I think is a good enhancement to the library, but wouldn't it be better to just use the sbt-tyepelevel plugin directly on the new Cats-OS ™ library instead? 🤔

**Comment by lenguyenthanh** [comment]
mm, I thought We'll use this repo directly 😓 let's sync on this.

**Comment by TonioGela** [comment]
> mm, I thought We'll use this repo directly 😓 let's sync on this.

Yep, THIS repo is going to become the "Cats-OS" library :)
