### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by TonioGela** [davenverse/shellfish#74]
As seen [here](https://github.com/davenverse/shellfish/actions/runs/9835028577/job/27147896395) the test `"We should create and delete recursively directories"` is flaky and needs fixing as it is occuring way too often.

@Hombre-x can you take care of it?

**Comment by Hombre-x** [comment]
Yup, let me see what's going on with it

**Comment by Hombre-x** [comment]
I think I just saw what happened, I left the `tempDir` outside the `forall` function. I'm going to run the test for some time to see if it solves the issue and push the changes

**Comment by lenguyenthanh** [comment]
close by #75
